DROP TRIGGER IF EXISTS items_au;
DROP TRIGGER IF EXISTS items_ad;
DROP TRIGGER IF EXISTS items_ai;

DROP TABLE IF EXISTS items_fts;
DROP TABLE IF EXISTS view_state;
DROP TABLE IF EXISTS item_tags;
DROP TABLE IF EXISTS tag_rules;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS sources;
