// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: nyttig/v1/nyttig.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Nyttig_AddSource_FullMethodName      = "/nyttig.v1.Nyttig/AddSource"
	Nyttig_RemoveSource_FullMethodName   = "/nyttig.v1.Nyttig/RemoveSource"
	Nyttig_UpdateSource_FullMethodName   = "/nyttig.v1.Nyttig/UpdateSource"
	Nyttig_ListSources_FullMethodName    = "/nyttig.v1.Nyttig/ListSources"
	Nyttig_RefreshSource_FullMethodName  = "/nyttig.v1.Nyttig/RefreshSource"
	Nyttig_AddTag_FullMethodName         = "/nyttig.v1.Nyttig/AddTag"
	Nyttig_RemoveTag_FullMethodName      = "/nyttig.v1.Nyttig/RemoveTag"
	Nyttig_ListTags_FullMethodName       = "/nyttig.v1.Nyttig/ListTags"
	Nyttig_AddTagRule_FullMethodName     = "/nyttig.v1.Nyttig/AddTagRule"
	Nyttig_RemoveTagRule_FullMethodName  = "/nyttig.v1.Nyttig/RemoveTagRule"
	Nyttig_ListTagRules_FullMethodName   = "/nyttig.v1.Nyttig/ListTagRules"
	Nyttig_StreamItems_FullMethodName    = "/nyttig.v1.Nyttig/StreamItems"
	Nyttig_Search_FullMethodName         = "/nyttig.v1.Nyttig/Search"
	Nyttig_MarkViewed_FullMethodName     = "/nyttig.v1.Nyttig/MarkViewed"
)

// NyttigClient is the client API for Nyttig service.
type NyttigClient interface {
	// Source management
	AddSource(ctx context.Context, in *AddSourceRequest, opts ...grpc.CallOption) (*Source, error)
	RemoveSource(ctx context.Context, in *RemoveSourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateSource(ctx context.Context, in *UpdateSourceRequest, opts ...grpc.CallOption) (*Source, error)
	ListSources(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSourcesResponse, error)
	RefreshSource(ctx context.Context, in *RefreshSourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Tag management
	AddTag(ctx context.Context, in *AddTagRequest, opts ...grpc.CallOption) (*Tag, error)
	RemoveTag(ctx context.Context, in *RemoveTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListTags(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTagsResponse, error)
	// Tag rules
	AddTagRule(ctx context.Context, in *AddTagRuleRequest, opts ...grpc.CallOption) (*TagRule, error)
	RemoveTagRule(ctx context.Context, in *RemoveTagRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListTagRules(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTagRulesResponse, error)
	// Core feed stream (bidirectional)
	StreamItems(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
	// Full-text search
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// View tracking
	MarkViewed(ctx context.Context, in *MarkViewedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type nyttigClient struct {
	cc grpc.ClientConnInterface
}

func NewNyttigClient(cc grpc.ClientConnInterface) NyttigClient {
	return &nyttigClient{cc}
}

func (c *nyttigClient) AddSource(ctx context.Context, in *AddSourceRequest, opts ...grpc.CallOption) (*Source, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Source)
	err := c.cc.Invoke(ctx, Nyttig_AddSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) RemoveSource(ctx context.Context, in *RemoveSourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nyttig_RemoveSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) UpdateSource(ctx context.Context, in *UpdateSourceRequest, opts ...grpc.CallOption) (*Source, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Source)
	err := c.cc.Invoke(ctx, Nyttig_UpdateSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) ListSources(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSourcesResponse)
	err := c.cc.Invoke(ctx, Nyttig_ListSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) RefreshSource(ctx context.Context, in *RefreshSourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nyttig_RefreshSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) AddTag(ctx context.Context, in *AddTagRequest, opts ...grpc.CallOption) (*Tag, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tag)
	err := c.cc.Invoke(ctx, Nyttig_AddTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) RemoveTag(ctx context.Context, in *RemoveTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nyttig_RemoveTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) ListTags(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, Nyttig_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) AddTagRule(ctx context.Context, in *AddTagRuleRequest, opts ...grpc.CallOption) (*TagRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagRule)
	err := c.cc.Invoke(ctx, Nyttig_AddTagRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) RemoveTagRule(ctx context.Context, in *RemoveTagRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nyttig_RemoveTagRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) ListTagRules(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTagRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagRulesResponse)
	err := c.cc.Invoke(ctx, Nyttig_ListTagRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) StreamItems(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Nyttig_ServiceDesc.Streams[0], Nyttig_StreamItems_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Nyttig_StreamItemsClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

func (c *nyttigClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, Nyttig_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) MarkViewed(ctx context.Context, in *MarkViewedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nyttig_MarkViewed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NyttigServer is the server API for Nyttig service.
// All implementations must embed UnimplementedNyttigServer for forward compatibility.
type NyttigServer interface {
	// Source management
	AddSource(context.Context, *AddSourceRequest) (*Source, error)
	RemoveSource(context.Context, *RemoveSourceRequest) (*emptypb.Empty, error)
	UpdateSource(context.Context, *UpdateSourceRequest) (*Source, error)
	ListSources(context.Context, *emptypb.Empty) (*ListSourcesResponse, error)
	RefreshSource(context.Context, *RefreshSourceRequest) (*emptypb.Empty, error)
	// Tag management
	AddTag(context.Context, *AddTagRequest) (*Tag, error)
	RemoveTag(context.Context, *RemoveTagRequest) (*emptypb.Empty, error)
	ListTags(context.Context, *emptypb.Empty) (*ListTagsResponse, error)
	// Tag rules
	AddTagRule(context.Context, *AddTagRuleRequest) (*TagRule, error)
	RemoveTagRule(context.Context, *RemoveTagRuleRequest) (*emptypb.Empty, error)
	ListTagRules(context.Context, *emptypb.Empty) (*ListTagRulesResponse, error)
	// Core feed stream (bidirectional)
	StreamItems(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	// Full-text search
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// View tracking
	MarkViewed(context.Context, *MarkViewedRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedNyttigServer()
}

// UnimplementedNyttigServer must be embedded to have forward compatible implementations.
type UnimplementedNyttigServer struct{}

func (UnimplementedNyttigServer) AddSource(context.Context, *AddSourceRequest) (*Source, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSource not implemented")
}

func (UnimplementedNyttigServer) RemoveSource(context.Context, *RemoveSourceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSource not implemented")
}

func (UnimplementedNyttigServer) UpdateSource(context.Context, *UpdateSourceRequest) (*Source, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSource not implemented")
}

func (UnimplementedNyttigServer) ListSources(context.Context, *emptypb.Empty) (*ListSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSources not implemented")
}

func (UnimplementedNyttigServer) RefreshSource(context.Context, *RefreshSourceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshSource not implemented")
}

func (UnimplementedNyttigServer) AddTag(context.Context, *AddTagRequest) (*Tag, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTag not implemented")
}

func (UnimplementedNyttigServer) RemoveTag(context.Context, *RemoveTagRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTag not implemented")
}

func (UnimplementedNyttigServer) ListTags(context.Context, *emptypb.Empty) (*ListTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTags not implemented")
}

func (UnimplementedNyttigServer) AddTagRule(context.Context, *AddTagRuleRequest) (*TagRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTagRule not implemented")
}

func (UnimplementedNyttigServer) RemoveTagRule(context.Context, *RemoveTagRuleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTagRule not implemented")
}

func (UnimplementedNyttigServer) ListTagRules(context.Context, *emptypb.Empty) (*ListTagRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTagRules not implemented")
}

func (UnimplementedNyttigServer) StreamItems(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamItems not implemented")
}

func (UnimplementedNyttigServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}

func (UnimplementedNyttigServer) MarkViewed(context.Context, *MarkViewedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkViewed not implemented")
}

func (UnimplementedNyttigServer) mustEmbedUnimplementedNyttigServer() {}
func (UnimplementedNyttigServer) testEmbeddedByValue()               {}

// UnsafeNyttigServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NyttigServer will
// result in compilation errors.
type UnsafeNyttigServer interface {
	mustEmbedUnimplementedNyttigServer()
}

func RegisterNyttigServer(s grpc.ServiceRegistrar, srv NyttigServer) {
	// If the following call panics, it indicates UnimplementedNyttigServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Nyttig_ServiceDesc, srv)
}

func _Nyttig_AddSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).AddSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_AddSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).AddSource(ctx, req.(*AddSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_RemoveSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).RemoveSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_RemoveSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).RemoveSource(ctx, req.(*RemoveSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_UpdateSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).UpdateSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_UpdateSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).UpdateSource(ctx, req.(*UpdateSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_ListSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).ListSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_ListSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).ListSources(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_RefreshSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).RefreshSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_RefreshSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).RefreshSource(ctx, req.(*RefreshSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_AddTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).AddTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_AddTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).AddTag(ctx, req.(*AddTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_RemoveTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).RemoveTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_RemoveTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).RemoveTag(ctx, req.(*RemoveTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).ListTags(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_AddTagRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTagRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).AddTagRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_AddTagRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).AddTagRule(ctx, req.(*AddTagRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_RemoveTagRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTagRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).RemoveTagRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_RemoveTagRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).RemoveTagRule(ctx, req.(*RemoveTagRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_ListTagRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).ListTagRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_ListTagRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).ListTagRules(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_StreamItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NyttigServer).StreamItems(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Nyttig_StreamItemsServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

func _Nyttig_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_MarkViewed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkViewedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).MarkViewed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_MarkViewed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).MarkViewed(ctx, req.(*MarkViewedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Nyttig_ServiceDesc is the grpc.ServiceDesc for Nyttig service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nyttig_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nyttig.v1.Nyttig",
	HandlerType: (*NyttigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddSource",
			Handler:    _Nyttig_AddSource_Handler,
		},
		{
			MethodName: "RemoveSource",
			Handler:    _Nyttig_RemoveSource_Handler,
		},
		{
			MethodName: "UpdateSource",
			Handler:    _Nyttig_UpdateSource_Handler,
		},
		{
			MethodName: "ListSources",
			Handler:    _Nyttig_ListSources_Handler,
		},
		{
			MethodName: "RefreshSource",
			Handler:    _Nyttig_RefreshSource_Handler,
		},
		{
			MethodName: "AddTag",
			Handler:    _Nyttig_AddTag_Handler,
		},
		{
			MethodName: "RemoveTag",
			Handler:    _Nyttig_RemoveTag_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _Nyttig_ListTags_Handler,
		},
		{
			MethodName: "AddTagRule",
			Handler:    _Nyttig_AddTagRule_Handler,
		},
		{
			MethodName: "RemoveTagRule",
			Handler:    _Nyttig_RemoveTagRule_Handler,
		},
		{
			MethodName: "ListTagRules",
			Handler:    _Nyttig_ListTagRules_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Nyttig_Search_Handler,
		},
		{
			MethodName: "MarkViewed",
			Handler:    _Nyttig_MarkViewed_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamItems",
			Handler:       _Nyttig_StreamItems_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "nyttig/v1/nyttig.proto",
}
