// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: nyttig/v1/nyttig.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // rss, atom
	RefreshSec    int32                  `protobuf:"varint,5,opt,name=refresh_sec,json=refreshSec,proto3" json:"refresh_sec,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastFetch     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_fetch,json=lastFetch,proto3" json:"last_fetch,omitempty"`
	FetchError    string                 `protobuf:"bytes,9,opt,name=fetch_error,json=fetchError,proto3" json:"fetch_error,omitempty"`
	Color         string                 `protobuf:"bytes,10,opt,name=color,proto3" json:"color,omitempty"`               // hex color, e.g. "#FF6600"
	Abbreviation  string                 `protobuf:"bytes,11,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"` // short display name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{0}
}

func (x *Source) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Source) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Source) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Source) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Source) GetRefreshSec() int32 {
	if x != nil {
		return x.RefreshSec
	}
	return 0
}

func (x *Source) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Source) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Source) GetLastFetch() *timestamppb.Timestamp {
	if x != nil {
		return x.LastFetch
	}
	return nil
}

func (x *Source) GetFetchError() string {
	if x != nil {
		return x.FetchError
	}
	return ""
}

func (x *Source) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Source) GetAbbreviation() string {
	if x != nil {
		return x.Abbreviation
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId      int64                  `protobuf:"varint,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceName    string                 `protobuf:"bytes,3,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	Guid          string                 `protobuf:"bytes,4,opt,name=guid,proto3" json:"guid,omitempty"`
	Link          string                 `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,8,opt,name=author,proto3" json:"author,omitempty"`
	Published     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=published,proto3" json:"published,omitempty"`
	FetchedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	Tags          []*Tag                 `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	Viewed        bool                   `protobuf:"varint,12,opt,name=viewed,proto3" json:"viewed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *Item) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *Item) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *Item) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Item) GetPublished() *timestamppb.Timestamp {
	if x != nil {
		return x.Published
	}
	return nil
}

func (x *Item) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

func (x *Item) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Item) GetViewed() bool {
	if x != nil {
		return x.Viewed
	}
	return false
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"` // hex color, e.g. "#FF6B35"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{2}
}

func (x *Tag) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type TagRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId      int64                  `protobuf:"varint,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // 0 = global
	TagId         int64                  `protobuf:"varint,3,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	TagName       string                 `protobuf:"bytes,4,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	Field         string                 `protobuf:"bytes,5,opt,name=field,proto3" json:"field,omitempty"`     // title, description, both
	Pattern       string                 `protobuf:"bytes,6,opt,name=pattern,proto3" json:"pattern,omitempty"` // regex pattern
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagRule) Reset() {
	*x = TagRule{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagRule) ProtoMessage() {}

func (x *TagRule) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagRule.ProtoReflect.Descriptor instead.
func (*TagRule) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{3}
}

func (x *TagRule) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagRule) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *TagRule) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *TagRule) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *TagRule) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *TagRule) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *TagRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type AddSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // rss, atom; defaults to "rss"
	RefreshSec    int32                  `protobuf:"varint,4,opt,name=refresh_sec,json=refreshSec,proto3" json:"refresh_sec,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`               // optional hex color for source chip
	Abbreviation  string                 `protobuf:"bytes,7,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"` // optional short display name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSourceRequest) Reset() {
	*x = AddSourceRequest{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSourceRequest) ProtoMessage() {}

func (x *AddSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSourceRequest.ProtoReflect.Descriptor instead.
func (*AddSourceRequest) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{4}
}

func (x *AddSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddSourceRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AddSourceRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddSourceRequest) GetRefreshSec() int32 {
	if x != nil {
		return x.RefreshSec
	}
	return 0
}

func (x *AddSourceRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AddSourceRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *AddSourceRequest) GetAbbreviation() string {
	if x != nil {
		return x.Abbreviation
	}
	return ""
}

type RemoveSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSourceRequest) Reset() {
	*x = RemoveSourceRequest{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSourceRequest) ProtoMessage() {}

func (x *RemoveSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSourceRequest.ProtoReflect.Descriptor instead.
func (*RemoveSourceRequest) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveSourceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// UpdateSourceRequest patches a source. Every mutable field has explicit
// presence: an unset field is left unchanged, a set field is written. For
// color and abbreviation, setting an empty string clears the value.
type UpdateSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Url           *string                `protobuf:"bytes,3,opt,name=url,proto3,oneof" json:"url,omitempty"`
	Type          *string                `protobuf:"bytes,4,opt,name=type,proto3,oneof" json:"type,omitempty"`
	RefreshSec    *int32                 `protobuf:"varint,5,opt,name=refresh_sec,json=refreshSec,proto3,oneof" json:"refresh_sec,omitempty"`
	Enabled       *bool                  `protobuf:"varint,6,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	Color         *string                `protobuf:"bytes,7,opt,name=color,proto3,oneof" json:"color,omitempty"`
	Abbreviation  *string                `protobuf:"bytes,8,opt,name=abbreviation,proto3,oneof" json:"abbreviation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSourceRequest) Reset() {
	*x = UpdateSourceRequest{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSourceRequest) ProtoMessage() {}

func (x *UpdateSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateSourceRequest) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSourceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSourceRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateSourceRequest) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *UpdateSourceRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *UpdateSourceRequest) GetRefreshSec() int32 {
	if x != nil && x.RefreshSec != nil {
		return *x.RefreshSec
	}
	return 0
}

func (x *UpdateSourceRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *UpdateSourceRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *UpdateSourceRequest) GetAbbreviation() string {
	if x != nil && x.Abbreviation != nil {
		return *x.Abbreviation
	}
	return ""
}

type ListSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*Source              `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesResponse) Reset() {
	*x = ListSourcesResponse{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesResponse) ProtoMessage() {}

func (x *ListSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListSourcesResponse) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{7}
}

func (x *ListSourcesResponse) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

type RefreshSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      int64                  `protobuf:"varint,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // 0 = all sources
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSourceRequest) Reset() {
	*x = RefreshSourceRequest{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSourceRequest) ProtoMessage() {}

func (x *RefreshSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSourceRequest.ProtoReflect.Descriptor instead.
func (*RefreshSourceRequest) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshSourceRequest) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

type AddTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTagRequest) Reset() {
	*x = AddTagRequest{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTagRequest) ProtoMessage() {}

func (x *AddTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTagRequest.ProtoReflect.Descriptor instead.
func (*AddTagRequest) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{9}
}

func (x *AddTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddTagRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

// UpdateTagRequest patches a tag. Unset fields are left unchanged; setting
// color to an empty string clears it.
type UpdateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Color         *string                `protobuf:"bytes,3,opt,name=color,proto3,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagRequest) Reset() {
	*x = UpdateTagRequest{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagRequest) ProtoMessage() {}

func (x *UpdateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagRequest) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTagRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTagRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTagRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

type RemoveTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTagRequest) Reset() {
	*x = RemoveTagRequest{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTagRequest) ProtoMessage() {}

func (x *RemoveTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTagRequest.ProtoReflect.Descriptor instead.
func (*RemoveTagRequest) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveTagRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{12}
}

func (x *ListTagsResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AddTagRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      int64                  `protobuf:"varint,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // 0 = global
	TagId         int64                  `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"` // title, description, both
	Pattern       string                 `protobuf:"bytes,4,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTagRuleRequest) Reset() {
	*x = AddTagRuleRequest{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTagRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTagRuleRequest) ProtoMessage() {}

func (x *AddTagRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTagRuleRequest.ProtoReflect.Descriptor instead.
func (*AddTagRuleRequest) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{13}
}

func (x *AddTagRuleRequest) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *AddTagRuleRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *AddTagRuleRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *AddTagRuleRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *AddTagRuleRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type RemoveTagRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTagRuleRequest) Reset() {
	*x = RemoveTagRuleRequest{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTagRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTagRuleRequest) ProtoMessage() {}

func (x *RemoveTagRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTagRuleRequest.ProtoReflect.Descriptor instead.
func (*RemoveTagRuleRequest) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveTagRuleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListTagRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*TagRule             `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagRulesResponse) Reset() {
	*x = ListTagRulesResponse{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagRulesResponse) ProtoMessage() {}

func (x *ListTagRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagRulesResponse.ProtoReflect.Descriptor instead.
func (*ListTagRulesResponse) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{15}
}

func (x *ListTagRulesResponse) GetRules() []*TagRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// TestTagRuleRequest dry-runs a rule against recently fetched items without
// saving it. The pattern is validated exactly as AddTagRule validates it.
type TestTagRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      int64                  `protobuf:"varint,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // 0 = items from all sources
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`                        // title, description, both; defaults to "both"
	Pattern       string                 `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"` // max matches to return; default 20, max 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestTagRuleRequest) Reset() {
	*x = TestTagRuleRequest{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestTagRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTagRuleRequest) ProtoMessage() {}

func (x *TestTagRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTagRuleRequest.ProtoReflect.Descriptor instead.
func (*TestTagRuleRequest) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{16}
}

func (x *TestTagRuleRequest) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *TestTagRuleRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *TestTagRuleRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *TestTagRuleRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TestTagRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`      // matching items, newest first
	Scanned       int32                  `protobuf:"varint,2,opt,name=scanned,proto3" json:"scanned,omitempty"` // how many recent items were checked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestTagRuleResponse) Reset() {
	*x = TestTagRuleResponse{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestTagRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTagRuleResponse) ProtoMessage() {}

func (x *TestTagRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTagRuleResponse.ProtoReflect.Descriptor instead.
func (*TestTagRuleResponse) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{17}
}

func (x *TestTagRuleResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *TestTagRuleResponse) GetScanned() int32 {
	if x != nil {
		return x.Scanned
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	SourceId      int64                  `protobuf:"varint,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // 0 = all sources
	TagId         int64                  `protobuf:"varint,3,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`          // 0 = all tags
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                       // default: 100
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`                     // default: 0
	Sort          string                 `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort,omitempty"`                          // newest, oldest; default newest
	UnviewedOnly  bool                   `protobuf:"varint,7,opt,name=unviewed_only,json=unviewedOnly,proto3" json:"unviewed_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{18}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *SearchRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *SearchRequest) GetUnviewedOnly() bool {
	if x != nil {
		return x.UnviewedOnly
	}
	return false
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{19}
}

func (x *SearchResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type MarkViewedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIds       []int64                `protobuf:"varint,1,rep,packed,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkViewedRequest) Reset() {
	*x = MarkViewedRequest{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkViewedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkViewedRequest) ProtoMessage() {}

func (x *MarkViewedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkViewedRequest.ProtoReflect.Descriptor instead.
func (*MarkViewedRequest) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{20}
}

func (x *MarkViewedRequest) GetItemIds() []int64 {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientMessage_Filter
	Msg           isClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{21}
}

func (x *ClientMessage) GetMsg() isClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientMessage) GetFilter() *StreamFilter {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Filter); ok {
			return x.Filter
		}
	}
	return nil
}

type isClientMessage_Msg interface {
	isClientMessage_Msg()
}

type ClientMessage_Filter struct {
	Filter *StreamFilter `protobuf:"bytes,1,opt,name=filter,proto3,oneof"`
}

func (*ClientMessage_Filter) isClientMessage_Msg() {}

type StreamFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      int64                  `protobuf:"varint,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // 0 = all
	TagId         int64                  `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`          // 0 = all
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`                      // FTS5 query string, empty = no filter
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`                          // newest, oldest; default newest
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	UnviewedOnly  bool                   `protobuf:"varint,6,opt,name=unviewed_only,json=unviewedOnly,proto3" json:"unviewed_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFilter) Reset() {
	*x = StreamFilter{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFilter) ProtoMessage() {}

func (x *StreamFilter) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFilter.ProtoReflect.Descriptor instead.
func (*StreamFilter) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{22}
}

func (x *StreamFilter) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *StreamFilter) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *StreamFilter) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *StreamFilter) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *StreamFilter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *StreamFilter) GetUnviewedOnly() bool {
	if x != nil {
		return x.UnviewedOnly
	}
	return false
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_Item
	//	*ServerMessage_Reset_
	//	*ServerMessage_Complete
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{23}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetItem() *Item {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Item); ok {
			return x.Item
		}
	}
	return nil
}

func (x *ServerMessage) GetReset_() *Reset {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Reset_); ok {
			return x.Reset_
		}
	}
	return nil
}

func (x *ServerMessage) GetComplete() *Complete {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_Item struct {
	Item *Item `protobuf:"bytes,1,opt,name=item,proto3,oneof"`
}

type ServerMessage_Reset_ struct {
	Reset_ *Reset `protobuf:"bytes,2,opt,name=reset,proto3,oneof"`
}

type ServerMessage_Complete struct {
	Complete *Complete `protobuf:"bytes,3,opt,name=complete,proto3,oneof"`
}

func (*ServerMessage_Item) isServerMessage_Msg() {}

func (*ServerMessage_Reset_) isServerMessage_Msg() {}

func (*ServerMessage_Complete) isServerMessage_Msg() {}

type Reset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reset) Reset() {
	*x = Reset{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reset) ProtoMessage() {}

func (x *Reset) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reset.ProtoReflect.Descriptor instead.
func (*Reset) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{24}
}

type Complete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Complete) Reset() {
	*x = Complete{}
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Complete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Complete) ProtoMessage() {}

func (x *Complete) ProtoReflect() protoreflect.Message {
	mi := &file_nyttig_v1_nyttig_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Complete.ProtoReflect.Descriptor instead.
func (*Complete) Descriptor() ([]byte, []int) {
	return file_nyttig_v1_nyttig_proto_rawDescGZIP(), []int{25}
}

var File_nyttig_v1_nyttig_proto protoreflect.FileDescriptor

const file_nyttig_v1_nyttig_proto_rawDesc = "" +
	"\n" +
	"\x16nyttig/v1/nyttig.proto\x12\tnyttig.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x02\n" +
	"\x06Source\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1f\n" +
	"\vrefresh_sec\x18\x05 \x01(\x05R\n" +
	"refreshSec\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"last_fetch\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tlastFetch\x12\x1f\n" +
	"\vfetch_error\x18\t \x01(\tR\n" +
	"fetchError\x12\x14\n" +
	"\x05color\x18\n" +
	" \x01(\tR\x05color\x12\"\n" +
	"\fabbreviation\x18\v \x01(\tR\fabbreviation\"\xfd\x02\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\x03R\bsourceId\x12\x1f\n" +
	"\vsource_name\x18\x03 \x01(\tR\n" +
	"sourceName\x12\x12\n" +
	"\x04guid\x18\x04 \x01(\tR\x04guid\x12\x12\n" +
	"\x04link\x18\x05 \x01(\tR\x04link\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\b \x01(\tR\x06author\x128\n" +
	"\tpublished\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tpublished\x129\n" +
	"\n" +
	"fetched_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAt\x12\"\n" +
	"\x04tags\x18\v \x03(\v2\x0e.nyttig.v1.TagR\x04tags\x12\x16\n" +
	"\x06viewed\x18\f \x01(\bR\x06viewed\"?\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\"\xb4\x01\n" +
	"\aTagRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\x03R\bsourceId\x12\x15\n" +
	"\x06tag_id\x18\x03 \x01(\x03R\x05tagId\x12\x19\n" +
	"\btag_name\x18\x04 \x01(\tR\atagName\x12\x14\n" +
	"\x05field\x18\x05 \x01(\tR\x05field\x12\x18\n" +
	"\apattern\x18\x06 \x01(\tR\apattern\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\"\xc1\x01\n" +
	"\x10AddSourceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1f\n" +
	"\vrefresh_sec\x18\x04 \x01(\x05R\n" +
	"refreshSec\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12\"\n" +
	"\fabbreviation\x18\a \x01(\tR\fabbreviation\"%\n" +
	"\x13RemoveSourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc8\x02\n" +
	"\x13UpdateSourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x03 \x01(\tH\x01R\x03url\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x04 \x01(\tH\x02R\x04type\x88\x01\x01\x12$\n" +
	"\vrefresh_sec\x18\x05 \x01(\x05H\x03R\n" +
	"refreshSec\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x06 \x01(\bH\x04R\aenabled\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\a \x01(\tH\x05R\x05color\x88\x01\x01\x12'\n" +
	"\fabbreviation\x18\b \x01(\tH\x06R\fabbreviation\x88\x01\x01B\a\n" +
	"\x05_nameB\x06\n" +
	"\x04_urlB\a\n" +
	"\x05_typeB\x0e\n" +
	"\f_refresh_secB\n" +
	"\n" +
	"\b_enabledB\b\n" +
	"\x06_colorB\x0f\n" +
	"\r_abbreviation\"B\n" +
	"\x13ListSourcesResponse\x12+\n" +
	"\asources\x18\x01 \x03(\v2\x11.nyttig.v1.SourceR\asources\"3\n" +
	"\x14RefreshSourceRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\x03R\bsourceId\"9\n" +
	"\rAddTagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\"i\n" +
	"\x10UpdateTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x03 \x01(\tH\x01R\x05color\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_color\"\"\n" +
	"\x10RemoveTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"6\n" +
	"\x10ListTagsResponse\x12\"\n" +
	"\x04tags\x18\x01 \x03(\v2\x0e.nyttig.v1.TagR\x04tags\"\x93\x01\n" +
	"\x11AddTagRuleRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\x03R\bsourceId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\x03R\x05tagId\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\x12\x18\n" +
	"\apattern\x18\x04 \x01(\tR\apattern\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\"&\n" +
	"\x14RemoveTagRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"@\n" +
	"\x14ListTagRulesResponse\x12(\n" +
	"\x05rules\x18\x01 \x03(\v2\x12.nyttig.v1.TagRuleR\x05rules\"w\n" +
	"\x12TestTagRuleRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\x03R\bsourceId\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"V\n" +
	"\x13TestTagRuleResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.nyttig.v1.ItemR\x05items\x12\x18\n" +
	"\ascanned\x18\x02 \x01(\x05R\ascanned\"\xc0\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\x03R\bsourceId\x12\x15\n" +
	"\x06tag_id\x18\x03 \x01(\x03R\x05tagId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\tR\x04sort\x12#\n" +
	"\runviewed_only\x18\a \x01(\bR\funviewedOnly\"M\n" +
	"\x0eSearchResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.nyttig.v1.ItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\".\n" +
	"\x11MarkViewedRequest\x12\x19\n" +
	"\bitem_ids\x18\x01 \x03(\x03R\aitemIds\"I\n" +
	"\rClientMessage\x121\n" +
	"\x06filter\x18\x01 \x01(\v2\x17.nyttig.v1.StreamFilterH\x00R\x06filterB\x05\n" +
	"\x03msg\"\xa9\x01\n" +
	"\fStreamFilter\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\x03R\bsourceId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\x03R\x05tagId\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12#\n" +
	"\runviewed_only\x18\x06 \x01(\bR\funviewedOnly\"\x9a\x01\n" +
	"\rServerMessage\x12%\n" +
	"\x04item\x18\x01 \x01(\v2\x0f.nyttig.v1.ItemH\x00R\x04item\x12(\n" +
	"\x05reset\x18\x02 \x01(\v2\x10.nyttig.v1.ResetH\x00R\x05reset\x121\n" +
	"\bcomplete\x18\x03 \x01(\v2\x13.nyttig.v1.CompleteH\x00R\bcompleteB\x05\n" +
	"\x03msg\"\a\n" +
	"\x05Reset\"\n" +
	"\n" +
	"\bComplete2\xbd\b\n" +
	"\x06Nyttig\x12;\n" +
	"\tAddSource\x12\x1b.nyttig.v1.AddSourceRequest\x1a\x11.nyttig.v1.Source\x12F\n" +
	"\fRemoveSource\x12\x1e.nyttig.v1.RemoveSourceRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\fUpdateSource\x12\x1e.nyttig.v1.UpdateSourceRequest\x1a\x11.nyttig.v1.Source\x12E\n" +
	"\vListSources\x12\x16.google.protobuf.Empty\x1a\x1e.nyttig.v1.ListSourcesResponse\x12H\n" +
	"\rRefreshSource\x12\x1f.nyttig.v1.RefreshSourceRequest\x1a\x16.google.protobuf.Empty\x122\n" +
	"\x06AddTag\x12\x18.nyttig.v1.AddTagRequest\x1a\x0e.nyttig.v1.Tag\x128\n" +
	"\tUpdateTag\x12\x1b.nyttig.v1.UpdateTagRequest\x1a\x0e.nyttig.v1.Tag\x12@\n" +
	"\tRemoveTag\x12\x1b.nyttig.v1.RemoveTagRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\bListTags\x12\x16.google.protobuf.Empty\x1a\x1b.nyttig.v1.ListTagsResponse\x12>\n" +
	"\n" +
	"AddTagRule\x12\x1c.nyttig.v1.AddTagRuleRequest\x1a\x12.nyttig.v1.TagRule\x12H\n" +
	"\rRemoveTagRule\x12\x1f.nyttig.v1.RemoveTagRuleRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\fListTagRules\x12\x16.google.protobuf.Empty\x1a\x1f.nyttig.v1.ListTagRulesResponse\x12L\n" +
	"\vTestTagRule\x12\x1d.nyttig.v1.TestTagRuleRequest\x1a\x1e.nyttig.v1.TestTagRuleResponse\x12E\n" +
	"\vStreamItems\x12\x18.nyttig.v1.ClientMessage\x1a\x18.nyttig.v1.ServerMessage(\x010\x01\x12=\n" +
	"\x06Search\x12\x18.nyttig.v1.SearchRequest\x1a\x19.nyttig.v1.SearchResponse\x12B\n" +
	"\n" +
	"MarkViewed\x12\x1c.nyttig.v1.MarkViewedRequest\x1a\x16.google.protobuf.EmptyB3Z1github.com/sonhal/nyttig/internal/proto/nyttig/v1b\x06proto3"

var (
	file_nyttig_v1_nyttig_proto_rawDescOnce sync.Once
	file_nyttig_v1_nyttig_proto_rawDescData []byte
)

func file_nyttig_v1_nyttig_proto_rawDescGZIP() []byte {
	file_nyttig_v1_nyttig_proto_rawDescOnce.Do(func() {
		file_nyttig_v1_nyttig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nyttig_v1_nyttig_proto_rawDesc), len(file_nyttig_v1_nyttig_proto_rawDesc)))
	})
	return file_nyttig_v1_nyttig_proto_rawDescData
}

var file_nyttig_v1_nyttig_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_nyttig_v1_nyttig_proto_goTypes = []any{
	(*Source)(nil),                // 0: nyttig.v1.Source
	(*Item)(nil),                  // 1: nyttig.v1.Item
	(*Tag)(nil),                   // 2: nyttig.v1.Tag
	(*TagRule)(nil),               // 3: nyttig.v1.TagRule
	(*AddSourceRequest)(nil),      // 4: nyttig.v1.AddSourceRequest
	(*RemoveSourceRequest)(nil),   // 5: nyttig.v1.RemoveSourceRequest
	(*UpdateSourceRequest)(nil),   // 6: nyttig.v1.UpdateSourceRequest
	(*ListSourcesResponse)(nil),   // 7: nyttig.v1.ListSourcesResponse
	(*RefreshSourceRequest)(nil),  // 8: nyttig.v1.RefreshSourceRequest
	(*AddTagRequest)(nil),         // 9: nyttig.v1.AddTagRequest
	(*UpdateTagRequest)(nil),      // 10: nyttig.v1.UpdateTagRequest
	(*RemoveTagRequest)(nil),      // 11: nyttig.v1.RemoveTagRequest
	(*ListTagsResponse)(nil),      // 12: nyttig.v1.ListTagsResponse
	(*AddTagRuleRequest)(nil),     // 13: nyttig.v1.AddTagRuleRequest
	(*RemoveTagRuleRequest)(nil),  // 14: nyttig.v1.RemoveTagRuleRequest
	(*ListTagRulesResponse)(nil),  // 15: nyttig.v1.ListTagRulesResponse
	(*TestTagRuleRequest)(nil),    // 16: nyttig.v1.TestTagRuleRequest
	(*TestTagRuleResponse)(nil),   // 17: nyttig.v1.TestTagRuleResponse
	(*SearchRequest)(nil),         // 18: nyttig.v1.SearchRequest
	(*SearchResponse)(nil),        // 19: nyttig.v1.SearchResponse
	(*MarkViewedRequest)(nil),     // 20: nyttig.v1.MarkViewedRequest
	(*ClientMessage)(nil),         // 21: nyttig.v1.ClientMessage
	(*StreamFilter)(nil),          // 22: nyttig.v1.StreamFilter
	(*ServerMessage)(nil),         // 23: nyttig.v1.ServerMessage
	(*Reset)(nil),                 // 24: nyttig.v1.Reset
	(*Complete)(nil),              // 25: nyttig.v1.Complete
	(*timestamppb.Timestamp)(nil), // 26: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 27: google.protobuf.Empty
}
var file_nyttig_v1_nyttig_proto_depIdxs = []int32{
	26, // 0: nyttig.v1.Source.created_at:type_name -> google.protobuf.Timestamp
	26, // 1: nyttig.v1.Source.last_fetch:type_name -> google.protobuf.Timestamp
	26, // 2: nyttig.v1.Item.published:type_name -> google.protobuf.Timestamp
	26, // 3: nyttig.v1.Item.fetched_at:type_name -> google.protobuf.Timestamp
	2,  // 4: nyttig.v1.Item.tags:type_name -> nyttig.v1.Tag
	0,  // 5: nyttig.v1.ListSourcesResponse.sources:type_name -> nyttig.v1.Source
	2,  // 6: nyttig.v1.ListTagsResponse.tags:type_name -> nyttig.v1.Tag
	3,  // 7: nyttig.v1.ListTagRulesResponse.rules:type_name -> nyttig.v1.TagRule
	1,  // 8: nyttig.v1.TestTagRuleResponse.items:type_name -> nyttig.v1.Item
	1,  // 9: nyttig.v1.SearchResponse.items:type_name -> nyttig.v1.Item
	22, // 10: nyttig.v1.ClientMessage.filter:type_name -> nyttig.v1.StreamFilter
	1,  // 11: nyttig.v1.ServerMessage.item:type_name -> nyttig.v1.Item
	24, // 12: nyttig.v1.ServerMessage.reset:type_name -> nyttig.v1.Reset
	25, // 13: nyttig.v1.ServerMessage.complete:type_name -> nyttig.v1.Complete
	4,  // 14: nyttig.v1.Nyttig.AddSource:input_type -> nyttig.v1.AddSourceRequest
	5,  // 15: nyttig.v1.Nyttig.RemoveSource:input_type -> nyttig.v1.RemoveSourceRequest
	6,  // 16: nyttig.v1.Nyttig.UpdateSource:input_type -> nyttig.v1.UpdateSourceRequest
	27, // 17: nyttig.v1.Nyttig.ListSources:input_type -> google.protobuf.Empty
	8,  // 18: nyttig.v1.Nyttig.RefreshSource:input_type -> nyttig.v1.RefreshSourceRequest
	9,  // 19: nyttig.v1.Nyttig.AddTag:input_type -> nyttig.v1.AddTagRequest
	10, // 20: nyttig.v1.Nyttig.UpdateTag:input_type -> nyttig.v1.UpdateTagRequest
	11, // 21: nyttig.v1.Nyttig.RemoveTag:input_type -> nyttig.v1.RemoveTagRequest
	27, // 22: nyttig.v1.Nyttig.ListTags:input_type -> google.protobuf.Empty
	13, // 23: nyttig.v1.Nyttig.AddTagRule:input_type -> nyttig.v1.AddTagRuleRequest
	14, // 24: nyttig.v1.Nyttig.RemoveTagRule:input_type -> nyttig.v1.RemoveTagRuleRequest
	27, // 25: nyttig.v1.Nyttig.ListTagRules:input_type -> google.protobuf.Empty
	16, // 26: nyttig.v1.Nyttig.TestTagRule:input_type -> nyttig.v1.TestTagRuleRequest
	21, // 27: nyttig.v1.Nyttig.StreamItems:input_type -> nyttig.v1.ClientMessage
	18, // 28: nyttig.v1.Nyttig.Search:input_type -> nyttig.v1.SearchRequest
	20, // 29: nyttig.v1.Nyttig.MarkViewed:input_type -> nyttig.v1.MarkViewedRequest
	0,  // 30: nyttig.v1.Nyttig.AddSource:output_type -> nyttig.v1.Source
	27, // 31: nyttig.v1.Nyttig.RemoveSource:output_type -> google.protobuf.Empty
	0,  // 32: nyttig.v1.Nyttig.UpdateSource:output_type -> nyttig.v1.Source
	7,  // 33: nyttig.v1.Nyttig.ListSources:output_type -> nyttig.v1.ListSourcesResponse
	27, // 34: nyttig.v1.Nyttig.RefreshSource:output_type -> google.protobuf.Empty
	2,  // 35: nyttig.v1.Nyttig.AddTag:output_type -> nyttig.v1.Tag
	2,  // 36: nyttig.v1.Nyttig.UpdateTag:output_type -> nyttig.v1.Tag
	27, // 37: nyttig.v1.Nyttig.RemoveTag:output_type -> google.protobuf.Empty
	12, // 38: nyttig.v1.Nyttig.ListTags:output_type -> nyttig.v1.ListTagsResponse
	3,  // 39: nyttig.v1.Nyttig.AddTagRule:output_type -> nyttig.v1.TagRule
	27, // 40: nyttig.v1.Nyttig.RemoveTagRule:output_type -> google.protobuf.Empty
	15, // 41: nyttig.v1.Nyttig.ListTagRules:output_type -> nyttig.v1.ListTagRulesResponse
	17, // 42: nyttig.v1.Nyttig.TestTagRule:output_type -> nyttig.v1.TestTagRuleResponse
	23, // 43: nyttig.v1.Nyttig.StreamItems:output_type -> nyttig.v1.ServerMessage
	19, // 44: nyttig.v1.Nyttig.Search:output_type -> nyttig.v1.SearchResponse
	27, // 45: nyttig.v1.Nyttig.MarkViewed:output_type -> google.protobuf.Empty
	30, // [30:46] is the sub-list for method output_type
	14, // [14:30] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_nyttig_v1_nyttig_proto_init() }
func file_nyttig_v1_nyttig_proto_init() {
	if File_nyttig_v1_nyttig_proto != nil {
		return
	}
	file_nyttig_v1_nyttig_proto_msgTypes[6].OneofWrappers = []any{}
	file_nyttig_v1_nyttig_proto_msgTypes[10].OneofWrappers = []any{}
	file_nyttig_v1_nyttig_proto_msgTypes[21].OneofWrappers = []any{
		(*ClientMessage_Filter)(nil),
	}
	file_nyttig_v1_nyttig_proto_msgTypes[23].OneofWrappers = []any{
		(*ServerMessage_Item)(nil),
		(*ServerMessage_Reset_)(nil),
		(*ServerMessage_Complete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nyttig_v1_nyttig_proto_rawDesc), len(file_nyttig_v1_nyttig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nyttig_v1_nyttig_proto_goTypes,
		DependencyIndexes: file_nyttig_v1_nyttig_proto_depIdxs,
		MessageInfos:      file_nyttig_v1_nyttig_proto_msgTypes,
	}.Build()
	File_nyttig_v1_nyttig_proto = out.File
	file_nyttig_v1_nyttig_proto_goTypes = nil
	file_nyttig_v1_nyttig_proto_depIdxs = nil
}
