// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: nyttig/v1/nyttig.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Nyttig_AddSource_FullMethodName         = "/nyttig.v1.Nyttig/AddSource"
	Nyttig_RemoveSource_FullMethodName      = "/nyttig.v1.Nyttig/RemoveSource"
	Nyttig_UpdateSource_FullMethodName      = "/nyttig.v1.Nyttig/UpdateSource"
	Nyttig_ListSources_FullMethodName       = "/nyttig.v1.Nyttig/ListSources"
	Nyttig_RefreshSource_FullMethodName     = "/nyttig.v1.Nyttig/RefreshSource"
	Nyttig_AddTag_FullMethodName            = "/nyttig.v1.Nyttig/AddTag"
	Nyttig_UpdateTag_FullMethodName         = "/nyttig.v1.Nyttig/UpdateTag"
	Nyttig_RemoveTag_FullMethodName         = "/nyttig.v1.Nyttig/RemoveTag"
	Nyttig_ListTags_FullMethodName          = "/nyttig.v1.Nyttig/ListTags"
	Nyttig_AddTagRule_FullMethodName        = "/nyttig.v1.Nyttig/AddTagRule"
	Nyttig_RemoveTagRule_FullMethodName     = "/nyttig.v1.Nyttig/RemoveTagRule"
	Nyttig_ListTagRules_FullMethodName      = "/nyttig.v1.Nyttig/ListTagRules"
	Nyttig_TestTagRule_FullMethodName       = "/nyttig.v1.Nyttig/TestTagRule"
	Nyttig_AddSavedView_FullMethodName      = "/nyttig.v1.Nyttig/AddSavedView"
	Nyttig_UpdateSavedView_FullMethodName   = "/nyttig.v1.Nyttig/UpdateSavedView"
	Nyttig_RemoveSavedView_FullMethodName   = "/nyttig.v1.Nyttig/RemoveSavedView"
	Nyttig_ListSavedViews_FullMethodName    = "/nyttig.v1.Nyttig/ListSavedViews"
	Nyttig_ReorderSavedViews_FullMethodName = "/nyttig.v1.Nyttig/ReorderSavedViews"
	Nyttig_AddAssessor_FullMethodName       = "/nyttig.v1.Nyttig/AddAssessor"
	Nyttig_UpdateAssessor_FullMethodName    = "/nyttig.v1.Nyttig/UpdateAssessor"
	Nyttig_RemoveAssessor_FullMethodName    = "/nyttig.v1.Nyttig/RemoveAssessor"
	Nyttig_ListAssessors_FullMethodName     = "/nyttig.v1.Nyttig/ListAssessors"
	Nyttig_PutAssessment_FullMethodName     = "/nyttig.v1.Nyttig/PutAssessment"
	Nyttig_RemoveAssessment_FullMethodName  = "/nyttig.v1.Nyttig/RemoveAssessment"
	Nyttig_StreamItems_FullMethodName       = "/nyttig.v1.Nyttig/StreamItems"
	Nyttig_Search_FullMethodName            = "/nyttig.v1.Nyttig/Search"
	Nyttig_MarkViewed_FullMethodName        = "/nyttig.v1.Nyttig/MarkViewed"
)

// NyttigClient is the client API for Nyttig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NyttigClient interface {
	// Source management
	AddSource(ctx context.Context, in *AddSourceRequest, opts ...grpc.CallOption) (*Source, error)
	RemoveSource(ctx context.Context, in *RemoveSourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateSource(ctx context.Context, in *UpdateSourceRequest, opts ...grpc.CallOption) (*Source, error)
	ListSources(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSourcesResponse, error)
	RefreshSource(ctx context.Context, in *RefreshSourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Tag management
	AddTag(ctx context.Context, in *AddTagRequest, opts ...grpc.CallOption) (*Tag, error)
	UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*Tag, error)
	RemoveTag(ctx context.Context, in *RemoveTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListTags(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTagsResponse, error)
	// Tag rules
	AddTagRule(ctx context.Context, in *AddTagRuleRequest, opts ...grpc.CallOption) (*TagRule, error)
	RemoveTagRule(ctx context.Context, in *RemoveTagRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListTagRules(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTagRulesResponse, error)
	TestTagRule(ctx context.Context, in *TestTagRuleRequest, opts ...grpc.CallOption) (*TestTagRuleResponse, error)
	// Saved views
	AddSavedView(ctx context.Context, in *AddSavedViewRequest, opts ...grpc.CallOption) (*SavedView, error)
	UpdateSavedView(ctx context.Context, in *UpdateSavedViewRequest, opts ...grpc.CallOption) (*SavedView, error)
	RemoveSavedView(ctx context.Context, in *RemoveSavedViewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListSavedViews(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSavedViewsResponse, error)
	ReorderSavedViews(ctx context.Context, in *ReorderSavedViewsRequest, opts ...grpc.CallOption) (*ListSavedViewsResponse, error)
	// Assessors and assessments
	AddAssessor(ctx context.Context, in *AddAssessorRequest, opts ...grpc.CallOption) (*Assessor, error)
	UpdateAssessor(ctx context.Context, in *UpdateAssessorRequest, opts ...grpc.CallOption) (*Assessor, error)
	RemoveAssessor(ctx context.Context, in *RemoveAssessorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListAssessors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAssessorsResponse, error)
	PutAssessment(ctx context.Context, in *PutAssessmentRequest, opts ...grpc.CallOption) (*Assessment, error)
	RemoveAssessment(ctx context.Context, in *RemoveAssessmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Core feed stream (bidirectional)
	StreamItems(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
	// Full-text search
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// View tracking
	MarkViewed(ctx context.Context, in *MarkViewedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type nyttigClient struct {
	cc grpc.ClientConnInterface
}

func NewNyttigClient(cc grpc.ClientConnInterface) NyttigClient {
	return &nyttigClient{cc}
}

func (c *nyttigClient) AddSource(ctx context.Context, in *AddSourceRequest, opts ...grpc.CallOption) (*Source, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Source)
	err := c.cc.Invoke(ctx, Nyttig_AddSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) RemoveSource(ctx context.Context, in *RemoveSourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nyttig_RemoveSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) UpdateSource(ctx context.Context, in *UpdateSourceRequest, opts ...grpc.CallOption) (*Source, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Source)
	err := c.cc.Invoke(ctx, Nyttig_UpdateSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) ListSources(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSourcesResponse)
	err := c.cc.Invoke(ctx, Nyttig_ListSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) RefreshSource(ctx context.Context, in *RefreshSourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nyttig_RefreshSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) AddTag(ctx context.Context, in *AddTagRequest, opts ...grpc.CallOption) (*Tag, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tag)
	err := c.cc.Invoke(ctx, Nyttig_AddTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*Tag, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tag)
	err := c.cc.Invoke(ctx, Nyttig_UpdateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) RemoveTag(ctx context.Context, in *RemoveTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nyttig_RemoveTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) ListTags(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, Nyttig_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) AddTagRule(ctx context.Context, in *AddTagRuleRequest, opts ...grpc.CallOption) (*TagRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagRule)
	err := c.cc.Invoke(ctx, Nyttig_AddTagRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) RemoveTagRule(ctx context.Context, in *RemoveTagRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nyttig_RemoveTagRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) ListTagRules(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTagRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagRulesResponse)
	err := c.cc.Invoke(ctx, Nyttig_ListTagRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) TestTagRule(ctx context.Context, in *TestTagRuleRequest, opts ...grpc.CallOption) (*TestTagRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestTagRuleResponse)
	err := c.cc.Invoke(ctx, Nyttig_TestTagRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) AddSavedView(ctx context.Context, in *AddSavedViewRequest, opts ...grpc.CallOption) (*SavedView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SavedView)
	err := c.cc.Invoke(ctx, Nyttig_AddSavedView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) UpdateSavedView(ctx context.Context, in *UpdateSavedViewRequest, opts ...grpc.CallOption) (*SavedView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SavedView)
	err := c.cc.Invoke(ctx, Nyttig_UpdateSavedView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) RemoveSavedView(ctx context.Context, in *RemoveSavedViewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nyttig_RemoveSavedView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) ListSavedViews(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSavedViewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSavedViewsResponse)
	err := c.cc.Invoke(ctx, Nyttig_ListSavedViews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) ReorderSavedViews(ctx context.Context, in *ReorderSavedViewsRequest, opts ...grpc.CallOption) (*ListSavedViewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSavedViewsResponse)
	err := c.cc.Invoke(ctx, Nyttig_ReorderSavedViews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) AddAssessor(ctx context.Context, in *AddAssessorRequest, opts ...grpc.CallOption) (*Assessor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Assessor)
	err := c.cc.Invoke(ctx, Nyttig_AddAssessor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) UpdateAssessor(ctx context.Context, in *UpdateAssessorRequest, opts ...grpc.CallOption) (*Assessor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Assessor)
	err := c.cc.Invoke(ctx, Nyttig_UpdateAssessor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) RemoveAssessor(ctx context.Context, in *RemoveAssessorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nyttig_RemoveAssessor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) ListAssessors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAssessorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAssessorsResponse)
	err := c.cc.Invoke(ctx, Nyttig_ListAssessors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) PutAssessment(ctx context.Context, in *PutAssessmentRequest, opts ...grpc.CallOption) (*Assessment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Assessment)
	err := c.cc.Invoke(ctx, Nyttig_PutAssessment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) RemoveAssessment(ctx context.Context, in *RemoveAssessmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nyttig_RemoveAssessment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) StreamItems(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Nyttig_ServiceDesc.Streams[0], Nyttig_StreamItems_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Nyttig_StreamItemsClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

func (c *nyttigClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, Nyttig_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nyttigClient) MarkViewed(ctx context.Context, in *MarkViewedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nyttig_MarkViewed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NyttigServer is the server API for Nyttig service.
// All implementations must embed UnimplementedNyttigServer
// for forward compatibility.
type NyttigServer interface {
	// Source management
	AddSource(context.Context, *AddSourceRequest) (*Source, error)
	RemoveSource(context.Context, *RemoveSourceRequest) (*emptypb.Empty, error)
	UpdateSource(context.Context, *UpdateSourceRequest) (*Source, error)
	ListSources(context.Context, *emptypb.Empty) (*ListSourcesResponse, error)
	RefreshSource(context.Context, *RefreshSourceRequest) (*emptypb.Empty, error)
	// Tag management
	AddTag(context.Context, *AddTagRequest) (*Tag, error)
	UpdateTag(context.Context, *UpdateTagRequest) (*Tag, error)
	RemoveTag(context.Context, *RemoveTagRequest) (*emptypb.Empty, error)
	ListTags(context.Context, *emptypb.Empty) (*ListTagsResponse, error)
	// Tag rules
	AddTagRule(context.Context, *AddTagRuleRequest) (*TagRule, error)
	RemoveTagRule(context.Context, *RemoveTagRuleRequest) (*emptypb.Empty, error)
	ListTagRules(context.Context, *emptypb.Empty) (*ListTagRulesResponse, error)
	TestTagRule(context.Context, *TestTagRuleRequest) (*TestTagRuleResponse, error)
	// Saved views
	AddSavedView(context.Context, *AddSavedViewRequest) (*SavedView, error)
	UpdateSavedView(context.Context, *UpdateSavedViewRequest) (*SavedView, error)
	RemoveSavedView(context.Context, *RemoveSavedViewRequest) (*emptypb.Empty, error)
	ListSavedViews(context.Context, *emptypb.Empty) (*ListSavedViewsResponse, error)
	ReorderSavedViews(context.Context, *ReorderSavedViewsRequest) (*ListSavedViewsResponse, error)
	// Assessors and assessments
	AddAssessor(context.Context, *AddAssessorRequest) (*Assessor, error)
	UpdateAssessor(context.Context, *UpdateAssessorRequest) (*Assessor, error)
	RemoveAssessor(context.Context, *RemoveAssessorRequest) (*emptypb.Empty, error)
	ListAssessors(context.Context, *emptypb.Empty) (*ListAssessorsResponse, error)
	PutAssessment(context.Context, *PutAssessmentRequest) (*Assessment, error)
	RemoveAssessment(context.Context, *RemoveAssessmentRequest) (*emptypb.Empty, error)
	// Core feed stream (bidirectional)
	StreamItems(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	// Full-text search
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// View tracking
	MarkViewed(context.Context, *MarkViewedRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedNyttigServer()
}

// UnimplementedNyttigServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNyttigServer struct{}

func (UnimplementedNyttigServer) AddSource(context.Context, *AddSourceRequest) (*Source, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSource not implemented")
}
func (UnimplementedNyttigServer) RemoveSource(context.Context, *RemoveSourceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSource not implemented")
}
func (UnimplementedNyttigServer) UpdateSource(context.Context, *UpdateSourceRequest) (*Source, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSource not implemented")
}
func (UnimplementedNyttigServer) ListSources(context.Context, *emptypb.Empty) (*ListSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSources not implemented")
}
func (UnimplementedNyttigServer) RefreshSource(context.Context, *RefreshSourceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshSource not implemented")
}
func (UnimplementedNyttigServer) AddTag(context.Context, *AddTagRequest) (*Tag, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTag not implemented")
}
func (UnimplementedNyttigServer) UpdateTag(context.Context, *UpdateTagRequest) (*Tag, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTag not implemented")
}
func (UnimplementedNyttigServer) RemoveTag(context.Context, *RemoveTagRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTag not implemented")
}
func (UnimplementedNyttigServer) ListTags(context.Context, *emptypb.Empty) (*ListTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedNyttigServer) AddTagRule(context.Context, *AddTagRuleRequest) (*TagRule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTagRule not implemented")
}
func (UnimplementedNyttigServer) RemoveTagRule(context.Context, *RemoveTagRuleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTagRule not implemented")
}
func (UnimplementedNyttigServer) ListTagRules(context.Context, *emptypb.Empty) (*ListTagRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTagRules not implemented")
}
func (UnimplementedNyttigServer) TestTagRule(context.Context, *TestTagRuleRequest) (*TestTagRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestTagRule not implemented")
}
func (UnimplementedNyttigServer) AddSavedView(context.Context, *AddSavedViewRequest) (*SavedView, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSavedView not implemented")
}
func (UnimplementedNyttigServer) UpdateSavedView(context.Context, *UpdateSavedViewRequest) (*SavedView, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSavedView not implemented")
}
func (UnimplementedNyttigServer) RemoveSavedView(context.Context, *RemoveSavedViewRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSavedView not implemented")
}
func (UnimplementedNyttigServer) ListSavedViews(context.Context, *emptypb.Empty) (*ListSavedViewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSavedViews not implemented")
}
func (UnimplementedNyttigServer) ReorderSavedViews(context.Context, *ReorderSavedViewsRequest) (*ListSavedViewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReorderSavedViews not implemented")
}
func (UnimplementedNyttigServer) AddAssessor(context.Context, *AddAssessorRequest) (*Assessor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAssessor not implemented")
}
func (UnimplementedNyttigServer) UpdateAssessor(context.Context, *UpdateAssessorRequest) (*Assessor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAssessor not implemented")
}
func (UnimplementedNyttigServer) RemoveAssessor(context.Context, *RemoveAssessorRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAssessor not implemented")
}
func (UnimplementedNyttigServer) ListAssessors(context.Context, *emptypb.Empty) (*ListAssessorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAssessors not implemented")
}
func (UnimplementedNyttigServer) PutAssessment(context.Context, *PutAssessmentRequest) (*Assessment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutAssessment not implemented")
}
func (UnimplementedNyttigServer) RemoveAssessment(context.Context, *RemoveAssessmentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAssessment not implemented")
}
func (UnimplementedNyttigServer) StreamItems(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamItems not implemented")
}
func (UnimplementedNyttigServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedNyttigServer) MarkViewed(context.Context, *MarkViewedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkViewed not implemented")
}
func (UnimplementedNyttigServer) mustEmbedUnimplementedNyttigServer() {}
func (UnimplementedNyttigServer) testEmbeddedByValue()                {}

// UnsafeNyttigServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NyttigServer will
// result in compilation errors.
type UnsafeNyttigServer interface {
	mustEmbedUnimplementedNyttigServer()
}

func RegisterNyttigServer(s grpc.ServiceRegistrar, srv NyttigServer) {
	// If the following call pancis, it indicates UnimplementedNyttigServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Nyttig_ServiceDesc, srv)
}

func _Nyttig_AddSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).AddSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_AddSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).AddSource(ctx, req.(*AddSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_RemoveSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).RemoveSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_RemoveSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).RemoveSource(ctx, req.(*RemoveSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_UpdateSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).UpdateSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_UpdateSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).UpdateSource(ctx, req.(*UpdateSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_ListSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).ListSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_ListSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).ListSources(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_RefreshSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).RefreshSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_RefreshSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).RefreshSource(ctx, req.(*RefreshSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_AddTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).AddTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_AddTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).AddTag(ctx, req.(*AddTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_UpdateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).UpdateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_UpdateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).UpdateTag(ctx, req.(*UpdateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_RemoveTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).RemoveTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_RemoveTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).RemoveTag(ctx, req.(*RemoveTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).ListTags(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_AddTagRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTagRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).AddTagRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_AddTagRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).AddTagRule(ctx, req.(*AddTagRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_RemoveTagRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTagRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).RemoveTagRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_RemoveTagRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).RemoveTagRule(ctx, req.(*RemoveTagRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_ListTagRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).ListTagRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_ListTagRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).ListTagRules(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_TestTagRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestTagRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).TestTagRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_TestTagRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).TestTagRule(ctx, req.(*TestTagRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_AddSavedView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSavedViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).AddSavedView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_AddSavedView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).AddSavedView(ctx, req.(*AddSavedViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_UpdateSavedView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSavedViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).UpdateSavedView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_UpdateSavedView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).UpdateSavedView(ctx, req.(*UpdateSavedViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_RemoveSavedView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSavedViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).RemoveSavedView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_RemoveSavedView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).RemoveSavedView(ctx, req.(*RemoveSavedViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_ListSavedViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).ListSavedViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_ListSavedViews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).ListSavedViews(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_ReorderSavedViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderSavedViewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).ReorderSavedViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_ReorderSavedViews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).ReorderSavedViews(ctx, req.(*ReorderSavedViewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_AddAssessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAssessorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).AddAssessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_AddAssessor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).AddAssessor(ctx, req.(*AddAssessorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_UpdateAssessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssessorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).UpdateAssessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_UpdateAssessor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).UpdateAssessor(ctx, req.(*UpdateAssessorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_RemoveAssessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAssessorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).RemoveAssessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_RemoveAssessor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).RemoveAssessor(ctx, req.(*RemoveAssessorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_ListAssessors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).ListAssessors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_ListAssessors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).ListAssessors(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_PutAssessment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).PutAssessment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_PutAssessment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).PutAssessment(ctx, req.(*PutAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_RemoveAssessment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).RemoveAssessment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_RemoveAssessment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).RemoveAssessment(ctx, req.(*RemoveAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_StreamItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NyttigServer).StreamItems(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Nyttig_StreamItemsServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

func _Nyttig_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nyttig_MarkViewed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkViewedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NyttigServer).MarkViewed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nyttig_MarkViewed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NyttigServer).MarkViewed(ctx, req.(*MarkViewedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Nyttig_ServiceDesc is the grpc.ServiceDesc for Nyttig service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nyttig_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nyttig.v1.Nyttig",
	HandlerType: (*NyttigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddSource",
			Handler:    _Nyttig_AddSource_Handler,
		},
		{
			MethodName: "RemoveSource",
			Handler:    _Nyttig_RemoveSource_Handler,
		},
		{
			MethodName: "UpdateSource",
			Handler:    _Nyttig_UpdateSource_Handler,
		},
		{
			MethodName: "ListSources",
			Handler:    _Nyttig_ListSources_Handler,
		},
		{
			MethodName: "RefreshSource",
			Handler:    _Nyttig_RefreshSource_Handler,
		},
		{
			MethodName: "AddTag",
			Handler:    _Nyttig_AddTag_Handler,
		},
		{
			MethodName: "UpdateTag",
			Handler:    _Nyttig_UpdateTag_Handler,
		},
		{
			MethodName: "RemoveTag",
			Handler:    _Nyttig_RemoveTag_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _Nyttig_ListTags_Handler,
		},
		{
			MethodName: "AddTagRule",
			Handler:    _Nyttig_AddTagRule_Handler,
		},
		{
			MethodName: "RemoveTagRule",
			Handler:    _Nyttig_RemoveTagRule_Handler,
		},
		{
			MethodName: "ListTagRules",
			Handler:    _Nyttig_ListTagRules_Handler,
		},
		{
			MethodName: "TestTagRule",
			Handler:    _Nyttig_TestTagRule_Handler,
		},
		{
			MethodName: "AddSavedView",
			Handler:    _Nyttig_AddSavedView_Handler,
		},
		{
			MethodName: "UpdateSavedView",
			Handler:    _Nyttig_UpdateSavedView_Handler,
		},
		{
			MethodName: "RemoveSavedView",
			Handler:    _Nyttig_RemoveSavedView_Handler,
		},
		{
			MethodName: "ListSavedViews",
			Handler:    _Nyttig_ListSavedViews_Handler,
		},
		{
			MethodName: "ReorderSavedViews",
			Handler:    _Nyttig_ReorderSavedViews_Handler,
		},
		{
			MethodName: "AddAssessor",
			Handler:    _Nyttig_AddAssessor_Handler,
		},
		{
			MethodName: "UpdateAssessor",
			Handler:    _Nyttig_UpdateAssessor_Handler,
		},
		{
			MethodName: "RemoveAssessor",
			Handler:    _Nyttig_RemoveAssessor_Handler,
		},
		{
			MethodName: "ListAssessors",
			Handler:    _Nyttig_ListAssessors_Handler,
		},
		{
			MethodName: "PutAssessment",
			Handler:    _Nyttig_PutAssessment_Handler,
		},
		{
			MethodName: "RemoveAssessment",
			Handler:    _Nyttig_RemoveAssessment_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Nyttig_Search_Handler,
		},
		{
			MethodName: "MarkViewed",
			Handler:    _Nyttig_MarkViewed_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamItems",
			Handler:       _Nyttig_StreamItems_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "nyttig/v1/nyttig.proto",
}
